name: LoginSystem

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build and push
        uses: docker/build-push-action@v2
        
      - name: Deploy to production
        uses: appleboy/ssh-action@master

      - name: Run docker-compose
        uses: appleboy/ssh-action@master
